### ISSUE TITLE
using simple factory to create cell with `item.type` may be more concise

### ISSUE THREAD

**Issue by wr-fenglei** [apferrarone/reactive-mvvm-table-view#1]
https://github.com/apferrarone/reactive-mvvm-table-view/blob/2e9687f4e1cb8421c47899642d2d1c3d1c4118c3/ProfileTableViewArchitecture/ProfileViewController.swift#L159

**Comment by apferrarone** [comment]
Sure yeah sometimes that is a good solution. For this repo the purpose was just to have some fun and play around w/ using a tableview diffing mechanism and view/ view model bindings so this was a simplest and succinct way to write the code. But definitely in a larger project or production project a factory might be a good idea. Thanks for the suggestion my friend :)
